### ISSUE TITLE
[question] MCU chip picture misleading

### ISSUE THREAD

**Issue by sonique6784** [CanUnesi/QMK-on-K6#1]
Hi,
thanks for this tutorial!
In your tutorial, there is a picture of the Keyboard chip and it doesn't show

"SN32F24x MCU", does it means that the chip on the picture cannot receive the QMK firmware?
Do you have a picture of a chip that can receive QMK?

![](https://github.com/CanUnesi/QMK-on-K6/raw/main/image0.jpg)

**Comment by CanUnesi** [comment]
Hi! I understand the confusion, it's the serial number that you're checking there, the chip model doesn't write directly on the chip, you check the serial number to find out if it's the correct model.

**Comment by sonique6784** [comment]
Ok, I see, I was expecting some sort of database somewhere, where we can check the serial number.

here is what Sonix flasher is showing for my Keychron K6 Hot Swappable RGB (mechanical switches).
<img width="712" alt="Sonix-flasher-k6-hotswapable-rgb" src="https://user-images.githubusercontent.com/7600467/131479369-bea464d9-d5dd-4543-be0e-3e930b922091.png">

**Comment by CanUnesi** [comment]
You need to put the keyboard into boot mode through shorting the boot pins. Then you'll be able to see the chip model in sonix flasher.
