### ISSUE TITLE
Step 8.1, I can no-longer download firmware anymore. Is there any other way to download via firmware?

### ISSUE THREAD

**Issue by cdytoby** [CanUnesi/QMK-on-K6#5]
![image](https://user-images.githubusercontent.com/15671368/223704941-7d344050-d7af-4052-a76f-b4d9c69ac183.png)

All Builds are not available to download firmware.

**Comment by CanUnesi** [comment]
You can build a fw following the guide, instead of downloading a pre-compiled one. I'm not exactly sure where you're referencing to in the picture.

**Comment by cdytoby** [comment]
You mentioned in the guide:

https://github.com/CanUnesi/QMK-on-K6#81-download-the-pre-compiled-firmware-archive-from-the-most-recent-run-from-here

That link "here" leads to GitHub CI actions, and you mentioned "most recent run", and that's the screenshot of most recent run. 

I can't download from there. So it seems I have to compile myself if I want VIA support, because entire step 8 is not doable now.

**Comment by CanUnesi** [comment]
You're right, the branch that I've filtered is no longer active, and as far as I can see, the most recent runs are not approved yet. Try to build a generic one yourself if you're in a hurry, I'll see what's up and update the guide soon.

**Comment by olkoxd** [comment]
is there any update on this?

**Comment by ludalex** [comment]
Facing the same issue.
